"""Node pools CLI commands.

Manages node pools configuration stored under ~/.kube/kitchen/config/<cluster>/node_pools.yaml.
"""
# Generated by Copilot

from __future__ import annotations

import logging
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import typer
import yaml

import paramiko
from rich.console import Console
from rich.json import JSON
from rich.panel import Panel
from rich.text import Text

from kitchen.config import ConfigManager
from kitchen.config.models import NodePool, NodePoolAzureConfig, NodePoolSSH, NodePoolsConfig
from kitchen.ssh import SSHSession
from kitchen.k8s.handlers.tailscale import TailscaleHandler
from kitchen.k8s.handlers.crio import CrioHandler
from kitchen.k8s.handlers.kubernetes_components import KubernetesComponentsHandler


logger = logging.getLogger(__name__)


node_pools_app = typer.Typer(help="Manage cluster node pools")

console = Console()

PRIVATE_KEY_MODE = 0o600
PUBLIC_KEY_MODE = 0o644
DEFAULT_KEYS_DIRNAME = "node-pools"


class NodePools:
    def __init__(self, console: Console) -> None:
        self._console = console

    def _resolve_effective_cluster_or_exit(self, cluster: str | None) -> str:
        _, eff_cluster, err = ConfigManager.resolve_config_path(cluster)
        if not eff_cluster:
            typer.secho(f"❌ {err}", fg=typer.colors.RED)
            raise typer.Exit(1)
        return eff_cluster

    def _generate_ssh_keypair(self, *, cluster: str, pool_name: str) -> tuple[str, str, str]:
        """Generate an RSA keypair and store it under the cluster config directory.

        Returns: (private_key_path, public_key_path, public_key_text)
        """

        # ~/.kube/kitchen/config/<cluster>/node-pools/<pool_name>/id_rsa(.pub)
        base_dir = ConfigManager.get_cluster_dir(cluster) / DEFAULT_KEYS_DIRNAME / pool_name
        base_dir.mkdir(parents=True, exist_ok=True)

        private_path = base_dir / "id_rsa"
        public_path = base_dir / "id_rsa.pub"

        key = paramiko.RSAKey.generate(4096)

        with private_path.open("w", encoding="utf-8") as f:
            key.write_private_key(f)
        os.chmod(private_path, PRIVATE_KEY_MODE)

        comment = f"kitchen:{cluster}:{pool_name}"
        public_key_text = f"{key.get_name()} {key.get_base64()} {comment}\n"
        public_path.write_text(public_key_text, encoding="utf-8")
        os.chmod(public_path, PUBLIC_KEY_MODE)

        return str(private_path), str(public_path), public_key_text.rstrip("\n")

    def _cleanup_generated_keys(self, private_path: str, public_path: str) -> None:
        for p in (private_path, public_path):
            try:
                Path(p).unlink(missing_ok=True)
            except Exception:
                pass

    def _load_pools_or_exit(self, cluster: str | None) -> NodePoolsConfig:
        pools_cfg, msg = ConfigManager.load_node_pools(cluster=cluster)
        if pools_cfg is None:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)
        return pools_cfg

    def _get_k8s_node_ips(self) -> set[str] | None:
        """Get set of internal IPs of all K8s nodes via kubectl.

        Returns None if kubectl fails (cluster not reachable).
        """
        import shutil
        import subprocess

        kubectl = shutil.which("kubectl")
        if not kubectl:
            return None

        cmd = [
            kubectl,
            "get",
            "nodes",
            "-o",
            "jsonpath={.items[*].status.addresses[?(@.type=='InternalIP')].address}",
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            return None

        ips = result.stdout.strip().split()
        return set(ips) if ips else set()

    def _fetch_join_credentials_from_master(
        self,
        *,
        master_user: str,
        master_host: str,
        ssh_key_path: str | None,
        verbose: bool = False,
    ) -> tuple[str | None, str | None, str | None]:
        """SSH to master and generate fresh kubeadm join credentials.

        Returns: (token, ca_cert_hash, error_message)
        On success: (token, hash, None)
        On failure: (None, None, error_message)
        """
        typer.secho(
            f"🔑 Fetching fresh join credentials from master {master_host}...",
            fg=typer.colors.CYAN,
        )

        try:
            with SSHSession(master_user, master_host, ssh_key_path, verbose) as ssh:
                stdout, stderr, code = ssh.run(
                    "kubeadm token create --print-join-command",
                    use_sudo=True,
                    timeout=30.0,
                )
                if code != 0:
                    return None, None, f"Failed to create token: {stderr or stdout}"

                join_cmd = stdout.strip()
                if not join_cmd:
                    return None, None, "Empty response from kubeadm token create"

                # Parse token
                token_match = re.search(r"--token\s+([a-z0-9]{6}\.[a-z0-9]{16})", join_cmd)
                if not token_match:
                    return None, None, f"Could not parse token from: {join_cmd}"
                token = token_match.group(1)

                # Parse CA hash
                hash_match = re.search(
                    r"--discovery-token-ca-cert-hash\s+(sha256:[a-f0-9]{64})", join_cmd
                )
                if not hash_match:
                    return None, None, f"Could not parse CA hash from: {join_cmd}"
                ca_hash = hash_match.group(1)

                typer.secho(f"✅ Got fresh token: {token[:10]}...", fg=typer.colors.GREEN)
                return token, ca_hash, None

        except Exception as e:
            return None, None, f"Failed to connect to master: {e}"

    def _prepare_phase(self, handler, name: str, verbose: bool) -> tuple[bool, str]:
        """Install + configure a component handler.

        Returns: (success, message)
        """
        inst = handler.check_installed()
        if not inst.ok:
            typer.secho(f"  🛠️  Installing {name}...", fg=typer.colors.YELLOW)
            if not handler.install():
                return False, f"Failed to install {name}"
            inst = handler.check_installed()
            if not inst.ok:
                return False, f"{name} installation check failed: {inst.message}"

        cfg = handler.check_config()
        if not cfg.ok:
            typer.secho(f"  🔧 Configuring {name}...", fg=typer.colors.YELLOW)
            if not handler.configure():
                return False, f"Failed to configure {name}"
            cfg = handler.check_config()
            if not cfg.ok:
                return False, f"{name} configuration failed: {cfg.message}"

        typer.secho(f"  ✅ {name} ready", fg=typer.colors.GREEN)
        return True, f"{name} ready"

    def _join_single_node(
        self,
        *,
        host: str,
        ssh_config: NodePoolSSH,
        endpoint: str,
        kubeadm_token: str,
        discovery_hash: str,
        tailscale_auth_key: str | None = None,
        kubernetes_version: str | None = None,
        verbose: bool = False,
    ) -> tuple[bool, str]:
        """Join a single node to the cluster via SSH.

        Prepares the node (tailscale, container runtime, kube components) then
        runs kubeadm join.

        Args:
            host: Public IP or hostname to SSH into
            ssh_config: SSH credentials from the pool
            endpoint: K8s API endpoint (host:port)
            kubeadm_token: kubeadm bootstrap token
            discovery_hash: CA cert hash (sha256:...)
            tailscale_auth_key: Optional Tailscale auth key for node setup
            kubernetes_version: K8s version (e.g., "v1.33")
            verbose: Enable verbose output

        Returns: (success, message)
        """
        user = ssh_config.username
        key_path = ssh_config.key_path
        password = ssh_config.password

        typer.secho(f"🔗 Joining node {host}...", fg=typer.colors.CYAN)

        try:
            with SSHSession(
                user=user,
                host=host,
                ssh_key_path=key_path,
                password=password,
                verbose=verbose,
            ) as ssh:
                # Check if node is already part of a cluster
                _, _, code = ssh.run(
                    "test -f /etc/kubernetes/kubelet.conf", use_sudo=True
                )
                if code == 0:
                    return False, "Node already joined (kubelet.conf exists)"

                # Phase 1: Tailscale
                typer.secho(f"  📦 Preparing node...", fg=typer.colors.CYAN)
                ts = TailscaleHandler(ssh, verbose)
                inst = ts.check_installed()
                if not inst.ok:
                    typer.secho(f"  🛠️  Installing tailscale...", fg=typer.colors.YELLOW)
                    if not ts.install():
                        return False, "Failed to install tailscale"
                cfg_ok = ts.check_config()
                if not cfg_ok.ok:
                    typer.secho(f"  🔧 Configuring tailscale...", fg=typer.colors.YELLOW)
                    ts.configure(auth_key=tailscale_auth_key)
                    cfg_ok = ts.check_config()
                if not cfg_ok.ok:
                    # Tailscale not required for join, just warn
                    typer.secho(f"  ⚠️  tailscale not ready: {cfg_ok.message}", fg=typer.colors.YELLOW)
                else:
                    typer.secho(f"  ✅ tailscale ready", fg=typer.colors.GREEN)

                # Phase 2: Container runtime (CRI-O)
                crio = CrioHandler(ssh, verbose, kubernetes_version=kubernetes_version)
                ok, msg = self._prepare_phase(crio, "container-runtime", verbose)
                if not ok:
                    return False, msg

                # Phase 3: Kubernetes components
                kube = KubernetesComponentsHandler(ssh, verbose, kubernetes_version=kubernetes_version)
                ok, msg = self._prepare_phase(kube, "kube-components", verbose)
                if not ok:
                    return False, msg


                # Build JoinConfiguration
                cri_socket = "unix:///var/run/crio/crio.sock"
                join_yaml_path = "/tmp/kitchen-join.yaml"

                # Get Tailscale IP for node-ip if available
                ts_ip_out, _, _ = ssh.run("tailscale ip -4", use_sudo=True)
                ts_ip = ts_ip_out.strip().splitlines()[-1] if ts_ip_out.strip() else ""

                join_yaml = (
                    "apiVersion: kubeadm.k8s.io/v1beta4\n"
                    "kind: JoinConfiguration\n"
                    "discovery:\n"
                    "  bootstrapToken:\n"
                    f"    token: {kubeadm_token}\n"
                    f"    apiServerEndpoint: {endpoint}\n"
                    "    caCertHashes:\n"
                    f"      - {discovery_hash}\n"
                    "nodeRegistration:\n"
                    f"  criSocket: {cri_socket}\n"
                )

                if ts_ip:
                    join_yaml += (
                        "  kubeletExtraArgs:\n"
                        "    - name: node-ip\n"
                        f"      value: {ts_ip}\n"
                    )

                # Write join config
                write_cmd = f"cat > {join_yaml_path} <<'EOF'\n{join_yaml}EOF\n"
                _, stderr, code = ssh.run(write_cmd, use_sudo=True)
                if code != 0:
                    return False, f"Failed to write JoinConfiguration: {stderr}"

                # Run kubeadm join
                typer.secho(f"  🚀 Running kubeadm join...", fg=typer.colors.BLUE)
                stdout, stderr, code = ssh.run(
                    f"kubeadm join --config {join_yaml_path}",
                    use_sudo=True,
                    timeout=120.0,
                )
                if code != 0:
                    return False, f"kubeadm join failed: {stderr or stdout}"

                return True, "Joined successfully"

        except Exception as e:
            return False, str(e)

    def list(self, *, cluster: str | None) -> None:
        pools_cfg = self._load_pools_or_exit(cluster)

        data = {
            "node_pools": [
                {
                    "name": p.name,
                    "region": p.region,
                    "size": p.size,
                    "provider": p.provider,
                    "azure": (
                        {
                            "vmss_name": p.azure.vmss_name,
                            "resource_group": p.azure.resource_group,
                        }
                        if p.azure is not None
                        else None
                    ),
                    "ssh": {
                        "username": p.ssh.username,
                        "password": p.ssh.password,
                        "key_path": p.ssh.key_path,
                        "port": p.ssh.port,
                    },
                }
                for p in pools_cfg.node_pools
            ]
        }

        self._console.print(JSON.from_data(data, indent=2, sort_keys=False))

    def show(self, *, cluster: str | None) -> None:
        pools_cfg = self._load_pools_or_exit(cluster)

        data = {
            "node_pools": [
                {
                    "name": p.name,
                    "region": p.region,
                    "size": p.size,
                    "provider": p.provider,
                    "azure": (
                        {
                            "vmss_name": p.azure.vmss_name,
                            "resource_group": p.azure.resource_group,
                        }
                        if p.azure is not None
                        else None
                    ),
                    "ssh": {
                        "username": p.ssh.username,
                        "password": p.ssh.password,
                        "key_path": p.ssh.key_path,
                        "port": p.ssh.port,
                    },
                }
                for p in pools_cfg.node_pools
            ]
        }

        typer.echo(yaml.safe_dump(data, sort_keys=False).rstrip())

    def add(
        self,
        *,
        name: str,
        region: str,
        size: int,
        provider: str,
        azure_vmss_name: Optional[str],
        azure_resource_group: Optional[str],
        ssh_username: str,
        ssh_password: Optional[str],
        ssh_key_path: Optional[str],
        ssh_port: int,
        cluster: str | None,
        overwrite: bool,
    ) -> None:
        eff_cluster = self._resolve_effective_cluster_or_exit(cluster)
        pools_cfg = self._load_pools_or_exit(cluster)

        existing_names = {p.name for p in pools_cfg.node_pools}
        if name in existing_names and not overwrite:
            typer.secho(
                f"❌ Pool '{name}' already exists. Use --overwrite to replace it.",
                fg=typer.colors.RED,
            )
            raise typer.Exit(1)

        generated_private = None
        generated_public = None
        generated_public_text = None

        if not ssh_password and not ssh_key_path:
            self._console.print("[yellow]🔐 No SSH credentials provided; generating keypair…[/yellow]")

            try:
                (
                    generated_private,
                    generated_public,
                    generated_public_text,
                ) = self._generate_ssh_keypair(cluster=eff_cluster, pool_name=name)
                ssh_key_path = generated_private
            except Exception as e:
                typer.secho(f"❌ Failed to generate SSH keypair: {e}", fg=typer.colors.RED)
                raise typer.Exit(1)

            msg = Text()
            msg.append(f"Node pool: {name}\n", style="bold")
            msg.append(f"Cluster: {eff_cluster}\n")
            msg.append("\nUpload the public key to your nodes/provider.\n", style="yellow")
            msg.append(f"Public:  {generated_public}\n", style="dim")
            msg.append(f"Private: {generated_private}", style="dim")
            self._console.print(Panel(msg, title="SSH key generated", border_style="yellow"))

            if not typer.confirm("Print public key now?"):
                self._cleanup_generated_keys(generated_private, generated_public)
                typer.secho("Aborted. Generated key files removed.", fg=typer.colors.RED)
                raise typer.Exit(1)

            self._console.print("[cyan bold]Public key:[/cyan bold]")
            typer.echo(generated_public_text)

        provider_norm = (provider or "").strip().lower()
        if provider_norm != "azure" and (azure_vmss_name or azure_resource_group):
            typer.secho(
                "❌ Azure-specific options were provided but --provider is not 'azure'.",
                fg=typer.colors.RED,
            )
            raise typer.Exit(1)

        azure_cfg = None
        if provider_norm == "azure":
            if bool(azure_vmss_name) ^ bool(azure_resource_group):
                typer.secho(
                    "❌ For Azure pools, both --azure-vmss-name and --azure-resource-group must be provided.",
                    fg=typer.colors.RED,
                )
                raise typer.Exit(1)
            if azure_vmss_name and azure_resource_group:
                azure_cfg = NodePoolAzureConfig(
                    vmss_name=azure_vmss_name,
                    resource_group=azure_resource_group,
                )

        new_pool = NodePool(
            name=name,
            region=region,
            size=size,
            provider=provider,
            azure=azure_cfg,
            ssh=NodePoolSSH(
                username=ssh_username,
                password=ssh_password,
                key_path=ssh_key_path,
                port=ssh_port,
            ),
        )

        new_list: list[NodePool] = [p for p in pools_cfg.node_pools if p.name != name]
        new_list.append(new_pool)

        ok, msg = ConfigManager.save_node_pools(
            NodePoolsConfig(node_pools=new_list),
            cluster=cluster,
            overwrite=False,
            merge=True,
        )
        if not ok:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)

        typer.secho(f"✅ Added node pool '{name}'", fg=typer.colors.GREEN)

    def remove(self, *, pool_name: str, cluster: str | None) -> None:
        pools_cfg = self._load_pools_or_exit(cluster)

        before = len(pools_cfg.node_pools)
        after_list = [p for p in pools_cfg.node_pools if p.name != pool_name]
        if len(after_list) == before:
            typer.secho(f"❌ Pool '{pool_name}' not found.", fg=typer.colors.RED)
            raise typer.Exit(1)

        ok, msg = ConfigManager.save_node_pools(
            NodePoolsConfig(node_pools=after_list),
            cluster=cluster,
            overwrite=True,
            merge=False,
        )
        if not ok:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)

        typer.secho(f"✅ Removed node pool '{pool_name}'", fg=typer.colors.GREEN)

    def scale(
        self,
        *,
        pool_name: str,
        size: int,
        cluster: str | None,
        auto_join: bool = False,
        master: str | None = None,
        endpoint: str | None = None,
        verbose: bool = False,
    ) -> None:
        if size < 0:
            typer.secho("❌ Size must be >= 0.", fg=typer.colors.RED)
            raise typer.Exit(1)

        pools_cfg = self._load_pools_or_exit(cluster)

        target_pool: NodePool | None = None
        target_provider: str | None = None
        target_azure = None
        updated = False
        new_list: list[NodePool] = []
        for p in pools_cfg.node_pools:
            if p.name != pool_name:
                new_list.append(p)
                continue

            target_pool = p
            target_provider = (p.provider or "").strip().lower()
            target_azure = p.azure
            new_list.append(
                NodePool(
                    name=p.name,
                    region=p.region,
                    size=size,
                    provider=p.provider,
                    azure=p.azure,
                    ssh=p.ssh,
                )
            )
            updated = True

        if not updated or target_pool is None:
            typer.secho(f"❌ Pool '{pool_name}' not found.", fg=typer.colors.RED)
            raise typer.Exit(1)

        instances_to_join: list[tuple[str, str]] = []  # (public_ip, name)

        # Provider-specific action (best-effort for now).
        if target_provider == "azure":
            from kitchen.node_provider import AzureNodeProvider

            try:
                typer.secho(f"⏳ Scaling Azure node pool '{pool_name}' to size={size}…", fg=typer.colors.YELLOW)
                if target_azure is None:
                    typer.secho(
                        f"❌ Pool '{pool_name}' is provider=azure but has no azure config.",
                        fg=typer.colors.RED,
                    )
                    raise typer.Exit(1)
                provider = AzureNodeProvider(
                    vmss_name=target_azure.vmss_name,
                    resource_group=target_azure.resource_group,
                )
                output = provider.scale_pool(pool_name, size)

                if output:
                    typer.echo(output)

                # After scaling, list instances and show their status
                typer.secho("\n📋 VMSS Instances:", fg=typer.colors.CYAN)
                instances = provider.list_instances()
                if not instances:
                    typer.echo("   (no instances)")
                else:
                    for inst in instances:
                        pub_ip = inst.public_ip or "N/A"
                        priv_ip = inst.private_ip or "N/A"
                        typer.echo(
                            f"   • {inst.name} (id={inst.instance_id}) "
                            f"public={pub_ip} private={priv_ip} "
                            f"state={inst.provisioning_state}/{inst.power_state}"
                        )

                # Get K8s node IPs to show join status (uses private IPs for internal cluster)
                k8s_node_ips = self._get_k8s_node_ips()
                if k8s_node_ips is not None:
                    typer.secho("\n🔗 Cluster Membership:", fg=typer.colors.CYAN)
                    for inst in instances:
                        if not inst.private_ip:
                            status = "❓ unknown (no IP)"
                        elif inst.private_ip in k8s_node_ips:
                            status = "✅ joined"
                        else:
                            status = "⏳ not joined"
                            # Collect for auto-join
                            if inst.public_ip:
                                instances_to_join.append((inst.public_ip, inst.name))
                        display = inst.public_ip or inst.private_ip or inst.name
                        typer.echo(f"   • {display}: {status}")
            except ValueError as e:
                typer.secho(f"❌ {e}", fg=typer.colors.RED)
                raise typer.Exit(1)
            except Exception as e:
                typer.secho(f"❌ Azure scale failed: {e}", fg=typer.colors.RED)
                raise typer.Exit(1)

        ok, msg = ConfigManager.save_node_pools(
            NodePoolsConfig(node_pools=new_list),
            cluster=cluster,
            overwrite=True,
            merge=False,
        )
        if not ok:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)

        typer.secho(f"✅ Scaled node pool '{pool_name}' to size={size}", fg=typer.colors.GREEN)

        # Auto-join logic
        if not instances_to_join:
            return

        if not auto_join:
            typer.secho(
                f"\n💡 {len(instances_to_join)} node(s) not joined. "
                "Use --auto-join to automatically join them.",
                fg=typer.colors.YELLOW,
            )
            return

        typer.secho(f"\n🔧 Auto-joining {len(instances_to_join)} node(s)...", fg=typer.colors.CYAN)

        # Get join credentials
        kubeadm_token: str | None = None
        discovery_hash: str | None = None
        eff_endpoint: str | None = endpoint

        if master:
            # Parse master string
            if "@" in master:
                master_user, master_host = master.split("@", 1)
            else:
                import getpass
                master_user = getpass.getuser()
                master_host = master

            token, ca_hash, err = self._fetch_join_credentials_from_master(
                master_user=master_user,
                master_host=master_host,
                ssh_key_path=target_pool.ssh.key_path,
                verbose=verbose,
            )
            if err:
                typer.secho(f"❌ Failed to get join credentials: {err}", fg=typer.colors.RED)
                return
            kubeadm_token = token
            discovery_hash = ca_hash
        else:
            # Load from saved secrets
            secrets, smsg = ConfigManager.load_cluster_secrets(cluster=cluster)
            if not secrets:
                typer.secho(f"❌ {smsg}", fg=typer.colors.RED)
                typer.secho(
                    "💡 Use --master user@host to fetch fresh credentials from master node.",
                    fg=typer.colors.YELLOW,
                )
                return
            if not secrets.kubeadm_token or not secrets.discovery_token_ca_cert_hash:
                typer.secho(
                    "❌ Missing kubeadm token or discovery hash in saved secrets.",
                    fg=typer.colors.RED,
                )
                typer.secho(
                    "💡 Use --master user@host to fetch fresh credentials from master node.",
                    fg=typer.colors.YELLOW,
                )
                return
            kubeadm_token = secrets.kubeadm_token
            discovery_hash = secrets.discovery_token_ca_cert_hash

        # Load secrets for tailscale auth key (for node prep)
        tailscale_auth_key: str | None = None
        secrets_for_ts, _ = ConfigManager.load_cluster_secrets(cluster=cluster)
        if secrets_for_ts:
            tailscale_auth_key = getattr(secrets_for_ts, 'tailscale_auth_key', None)

        # Determine endpoint and kubernetes_version from master config
        master_cfg, _ = ConfigManager.load_master_config(cluster=cluster)
        kubernetes_version: str | None = None

        if master_cfg:
            kubernetes_version = master_cfg.kubernetes_version

            # Determine endpoint if not provided
            if not eff_endpoint:
                # Prefer Tailscale IP (100.x.x.x), then first IP, then hostname
                for ip in master_cfg.ips or []:
                    if ip.startswith("100."):
                        eff_endpoint = f"{ip}:6443"
                        break
                if not eff_endpoint and master_cfg.ips:
                    eff_endpoint = f"{master_cfg.ips[0]}:6443"
                if not eff_endpoint and master_cfg.hostname:
                    eff_endpoint = f"{master_cfg.hostname}:6443"

        if not eff_endpoint:
            typer.secho(
                "❌ Could not determine API endpoint. Use --endpoint to specify.",
                fg=typer.colors.RED,
            )
            return

        # Join each node
        joined = 0
        failed = 0
        for pub_ip, name in instances_to_join:
            ok, msg = self._join_single_node(
                host=pub_ip,
                ssh_config=target_pool.ssh,
                endpoint=eff_endpoint,
                kubeadm_token=kubeadm_token,
                discovery_hash=discovery_hash,
                tailscale_auth_key=tailscale_auth_key,
                kubernetes_version=kubernetes_version,
                verbose=verbose,
            )
            if ok:
                typer.secho(f"  ✅ {name} ({pub_ip}): {msg}", fg=typer.colors.GREEN)
                joined += 1
            else:
                typer.secho(f"  ❌ {name} ({pub_ip}): {msg}", fg=typer.colors.RED)
                failed += 1

        typer.secho(
            f"\n📊 Join summary: {joined} succeeded, {failed} failed",
            fg=typer.colors.GREEN if failed == 0 else typer.colors.YELLOW,
        )


cli = NodePools(console)


@node_pools_app.command("list", help="List configured node pools")
def list_pools(
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    cli.list(cluster=cluster)


@node_pools_app.command("show", help="Show node pools config (YAML)")
def show_pools(
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    cli.show(cluster=cluster)


@node_pools_app.command("add", help="Add (or update) a node pool")
def add_pool(
    name: str = typer.Option(..., "--name", help="Node pool name"),
    region: str = typer.Option("global", "--region", help="Node pool region"),
    size: int = typer.Option(0, "--size", help="Number of nodes"),
    provider: str = typer.Option(..., "--provider", help="Provider name"),
    azure_vmss_name: Optional[str] = typer.Option(None, "--azure-vmss-name", help="Azure VMSS name (azure only)"),
    azure_resource_group: Optional[str] = typer.Option(
        None, "--azure-resource-group", help="Azure resource group (azure only)"
    ),
    ssh_username: str = typer.Option("root", "--ssh-username", help="SSH username (default: root)"),
    ssh_password: Optional[str] = typer.Option(None, "--ssh-password", help="SSH password (optional)"),
    ssh_key_path: Optional[str] = typer.Option(None, "--ssh-key-path", help="SSH private key path (optional)"),
    ssh_port: int = typer.Option(22, "--ssh-port", help="SSH port"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
    overwrite: bool = typer.Option(
        False,
        "--overwrite",
        help="Overwrite an existing pool with the same name (otherwise errors)",
    ),
) -> None:
    cli.add(
        name=name,
        region=region,
        size=size,
        provider=provider,
        azure_vmss_name=azure_vmss_name,
        azure_resource_group=azure_resource_group,
        ssh_username=ssh_username,
        ssh_password=ssh_password,
        ssh_key_path=ssh_key_path,
        ssh_port=ssh_port,
        cluster=cluster,
        overwrite=overwrite,
    )


@node_pools_app.command("remove", help="Remove a node pool by name")
def remove_pool(
    pool: Optional[str] = typer.Argument(None, help="Node pool name"),
    name: Optional[str] = typer.Option(None, "--name", help="Node pool name (alternative to positional arg)"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    pool_name = name or pool
    if not pool_name:
        typer.secho("❌ Missing node pool name. Provide it as an argument or via --name.", fg=typer.colors.RED)
        raise typer.Exit(1)

    cli.remove(pool_name=pool_name, cluster=cluster)


@node_pools_app.command("rm", help="Alias for remove")
def rm_pool(
    pool: Optional[str] = typer.Argument(None, help="Node pool name"),
    name: Optional[str] = typer.Option(None, "--name", help="Node pool name (alternative to positional arg)"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    pool_name = name or pool
    if not pool_name:
        typer.secho("❌ Missing node pool name. Provide it as an argument or via --name.", fg=typer.colors.RED)
        raise typer.Exit(1)

    cli.remove(pool_name=pool_name, cluster=cluster)


@node_pools_app.command("scale", help="Scale a node pool to a specific size")
def scale_pool(
    pool: Optional[str] = typer.Argument(None, help="Node pool name"),
    to: Optional[int] = typer.Argument(None, help="New size"),
    name: Optional[str] = typer.Option(None, "--name", help="Node pool name (alternative to positional arg)"),
    size: Optional[int] = typer.Option(None, "--size", help="New size (alternative to positional arg)"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
    auto_join: bool = typer.Option(
        False,
        "--auto-join",
        help="Automatically join un-joined nodes to the cluster after scaling up.",
    ),
    master: str | None = typer.Option(
        None,
        "--master",
        "-m",
        help="Master node user@host to fetch fresh join credentials (required for auto-join if no saved secrets).",
    ),
    endpoint: str | None = typer.Option(
        None,
        "--endpoint",
        help="K8s API endpoint (host:port) for kubeadm join. Auto-detected from config if omitted.",
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output."),
) -> None:
    pool_name = name or pool
    new_size = size if size is not None else to
    if not pool_name:
        typer.secho("❌ Missing node pool name. Provide it as an argument or via --name.", fg=typer.colors.RED)
        raise typer.Exit(1)
    if new_size is None:
        typer.secho("❌ Missing size. Provide it as an argument or via --size.", fg=typer.colors.RED)
        raise typer.Exit(1)

    cli.scale(
        pool_name=pool_name,
        size=new_size,
        cluster=cluster,
        auto_join=auto_join,
        master=master,
        endpoint=endpoint,
        verbose=verbose,
    )
