"""Node pools CLI commands.

Manages node pools configuration stored under ~/.kube/kitchen/config/<cluster>/node_pools.yaml.
"""
# Generated by Copilot

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import typer
import yaml

import paramiko
from rich.console import Console
from rich.json import JSON
from rich.panel import Panel
from rich.text import Text

from kitchen.config import ConfigManager
from kitchen.config.models import NodePool, NodePoolAzureConfig, NodePoolSSH, NodePoolsConfig


node_pools_app = typer.Typer(help="Manage cluster node pools")

console = Console()

PRIVATE_KEY_MODE = 0o600
PUBLIC_KEY_MODE = 0o644
DEFAULT_KEYS_DIRNAME = "node-pools"


class NodePools:
    def __init__(self, console: Console) -> None:
        self._console = console

    def _resolve_effective_cluster_or_exit(self, cluster: str | None) -> str:
        _, eff_cluster, err = ConfigManager.resolve_config_path(cluster)
        if not eff_cluster:
            typer.secho(f"❌ {err}", fg=typer.colors.RED)
            raise typer.Exit(1)
        return eff_cluster

    def _generate_ssh_keypair(self, *, cluster: str, pool_name: str) -> tuple[str, str, str]:
        """Generate an RSA keypair and store it under the cluster config directory.

        Returns: (private_key_path, public_key_path, public_key_text)
        """

        # ~/.kube/kitchen/config/<cluster>/node-pools/<pool_name>/id_rsa(.pub)
        base_dir = ConfigManager.get_cluster_dir(cluster) / DEFAULT_KEYS_DIRNAME / pool_name
        base_dir.mkdir(parents=True, exist_ok=True)

        private_path = base_dir / "id_rsa"
        public_path = base_dir / "id_rsa.pub"

        key = paramiko.RSAKey.generate(4096)

        with private_path.open("w", encoding="utf-8") as f:
            key.write_private_key(f)
        os.chmod(private_path, PRIVATE_KEY_MODE)

        comment = f"kitchen:{cluster}:{pool_name}"
        public_key_text = f"{key.get_name()} {key.get_base64()} {comment}\n"
        public_path.write_text(public_key_text, encoding="utf-8")
        os.chmod(public_path, PUBLIC_KEY_MODE)

        return str(private_path), str(public_path), public_key_text.rstrip("\n")

    def _cleanup_generated_keys(self, private_path: str, public_path: str) -> None:
        for p in (private_path, public_path):
            try:
                Path(p).unlink(missing_ok=True)
            except Exception:
                pass

    def _load_pools_or_exit(self, cluster: str | None) -> NodePoolsConfig:
        pools_cfg, msg = ConfigManager.load_node_pools(cluster=cluster)
        if pools_cfg is None:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)
        return pools_cfg

    def list(self, *, cluster: str | None) -> None:
        pools_cfg = self._load_pools_or_exit(cluster)

        data = {
            "node_pools": [
                {
                    "name": p.name,
                    "region": p.region,
                    "size": p.size,
                    "provider": p.provider,
                    "azure": (
                        {
                            "vmss_name": p.azure.vmss_name,
                            "resource_group": p.azure.resource_group,
                        }
                        if p.azure is not None
                        else None
                    ),
                    "ssh": {
                        "username": p.ssh.username,
                        "password": p.ssh.password,
                        "key_path": p.ssh.key_path,
                        "port": p.ssh.port,
                    },
                }
                for p in pools_cfg.node_pools
            ]
        }

        self._console.print(JSON.from_data(data, indent=2, sort_keys=False))

    def show(self, *, cluster: str | None) -> None:
        pools_cfg = self._load_pools_or_exit(cluster)

        data = {
            "node_pools": [
                {
                    "name": p.name,
                    "region": p.region,
                    "size": p.size,
                    "provider": p.provider,
                    "azure": (
                        {
                            "vmss_name": p.azure.vmss_name,
                            "resource_group": p.azure.resource_group,
                        }
                        if p.azure is not None
                        else None
                    ),
                    "ssh": {
                        "username": p.ssh.username,
                        "password": p.ssh.password,
                        "key_path": p.ssh.key_path,
                        "port": p.ssh.port,
                    },
                }
                for p in pools_cfg.node_pools
            ]
        }

        typer.echo(yaml.safe_dump(data, sort_keys=False).rstrip())

    def add(
        self,
        *,
        name: str,
        region: str,
        size: int,
        provider: str,
        azure_vmss_name: Optional[str],
        azure_resource_group: Optional[str],
        ssh_username: str,
        ssh_password: Optional[str],
        ssh_key_path: Optional[str],
        ssh_port: int,
        cluster: str | None,
        overwrite: bool,
    ) -> None:
        eff_cluster = self._resolve_effective_cluster_or_exit(cluster)
        pools_cfg = self._load_pools_or_exit(cluster)

        existing_names = {p.name for p in pools_cfg.node_pools}
        if name in existing_names and not overwrite:
            typer.secho(
                f"❌ Pool '{name}' already exists. Use --overwrite to replace it.",
                fg=typer.colors.RED,
            )
            raise typer.Exit(1)

        generated_private = None
        generated_public = None
        generated_public_text = None

        if not ssh_password and not ssh_key_path:
            self._console.print("[yellow]🔐 No SSH credentials provided; generating keypair…[/yellow]")

            try:
                (
                    generated_private,
                    generated_public,
                    generated_public_text,
                ) = self._generate_ssh_keypair(cluster=eff_cluster, pool_name=name)
                ssh_key_path = generated_private
            except Exception as e:
                typer.secho(f"❌ Failed to generate SSH keypair: {e}", fg=typer.colors.RED)
                raise typer.Exit(1)

            msg = Text()
            msg.append(f"Node pool: {name}\n", style="bold")
            msg.append(f"Cluster: {eff_cluster}\n")
            msg.append("\nUpload the public key to your nodes/provider.\n", style="yellow")
            msg.append(f"Public:  {generated_public}\n", style="dim")
            msg.append(f"Private: {generated_private}", style="dim")
            self._console.print(Panel(msg, title="SSH key generated", border_style="yellow"))

            if not typer.confirm("Print public key now?"):
                self._cleanup_generated_keys(generated_private, generated_public)
                typer.secho("Aborted. Generated key files removed.", fg=typer.colors.RED)
                raise typer.Exit(1)

            self._console.print("[cyan bold]Public key:[/cyan bold]")
            typer.echo(generated_public_text)

        provider_norm = (provider or "").strip().lower()
        if provider_norm != "azure" and (azure_vmss_name or azure_resource_group):
            typer.secho(
                "❌ Azure-specific options were provided but --provider is not 'azure'.",
                fg=typer.colors.RED,
            )
            raise typer.Exit(1)

        azure_cfg = None
        if provider_norm == "azure":
            if bool(azure_vmss_name) ^ bool(azure_resource_group):
                typer.secho(
                    "❌ For Azure pools, both --azure-vmss-name and --azure-resource-group must be provided.",
                    fg=typer.colors.RED,
                )
                raise typer.Exit(1)
            if azure_vmss_name and azure_resource_group:
                azure_cfg = NodePoolAzureConfig(
                    vmss_name=azure_vmss_name,
                    resource_group=azure_resource_group,
                )

        new_pool = NodePool(
            name=name,
            region=region,
            size=size,
            provider=provider,
            azure=azure_cfg,
            ssh=NodePoolSSH(
                username=ssh_username,
                password=ssh_password,
                key_path=ssh_key_path,
                port=ssh_port,
            ),
        )

        new_list: list[NodePool] = [p for p in pools_cfg.node_pools if p.name != name]
        new_list.append(new_pool)

        ok, msg = ConfigManager.save_node_pools(
            NodePoolsConfig(node_pools=new_list),
            cluster=cluster,
            overwrite=False,
            merge=True,
        )
        if not ok:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)

        typer.secho(f"✅ Added node pool '{name}'", fg=typer.colors.GREEN)

    def remove(self, *, pool_name: str, cluster: str | None) -> None:
        pools_cfg = self._load_pools_or_exit(cluster)

        before = len(pools_cfg.node_pools)
        after_list = [p for p in pools_cfg.node_pools if p.name != pool_name]
        if len(after_list) == before:
            typer.secho(f"❌ Pool '{pool_name}' not found.", fg=typer.colors.RED)
            raise typer.Exit(1)

        ok, msg = ConfigManager.save_node_pools(
            NodePoolsConfig(node_pools=after_list),
            cluster=cluster,
            overwrite=True,
            merge=False,
        )
        if not ok:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)

        typer.secho(f"✅ Removed node pool '{pool_name}'", fg=typer.colors.GREEN)

    def scale(self, *, pool_name: str, size: int, cluster: str | None) -> None:
        if size < 0:
            typer.secho("❌ Size must be >= 0.", fg=typer.colors.RED)
            raise typer.Exit(1)

        pools_cfg = self._load_pools_or_exit(cluster)

        target_provider: str | None = None
        target_azure = None
        updated = False
        new_list: list[NodePool] = []
        for p in pools_cfg.node_pools:
            if p.name != pool_name:
                new_list.append(p)
                continue

            target_provider = (p.provider or "").strip().lower()
            target_azure = p.azure
            new_list.append(
                NodePool(
                    name=p.name,
                    region=p.region,
                    size=size,
                    provider=p.provider,
                    azure=p.azure,
                    ssh=p.ssh,
                )
            )
            updated = True

        if not updated:
            typer.secho(f"❌ Pool '{pool_name}' not found.", fg=typer.colors.RED)
            raise typer.Exit(1)

        # Provider-specific action (best-effort for now).
        if target_provider == "azure":
            from kitchen.node_provider import AzureNodeProvider

            try:
                typer.secho(f"⏳ Scaling Azure node pool '{pool_name}' to size={size}…", fg=typer.colors.YELLOW)
                if target_azure is None:
                    typer.secho(
                        f"❌ Pool '{pool_name}' is provider=azure but has no azure config.",
                        fg=typer.colors.RED,
                    )
                    raise typer.Exit(1)
                output = AzureNodeProvider(
                    vmss_name=target_azure.vmss_name,
                    resource_group=target_azure.resource_group,
                ).scale_pool(pool_name, size)

                if output:
                    typer.echo(output)
            except ValueError as e:
                typer.secho(f"❌ {e}", fg=typer.colors.RED)
                raise typer.Exit(1)
            except Exception as e:
                typer.secho(f"❌ Azure scale failed: {e}", fg=typer.colors.RED)
                raise typer.Exit(1)

        ok, msg = ConfigManager.save_node_pools(
            NodePoolsConfig(node_pools=new_list),
            cluster=cluster,
            overwrite=True,
            merge=False,
        )
        if not ok:
            typer.secho(f"❌ {msg}", fg=typer.colors.RED)
            raise typer.Exit(1)

        typer.secho(f"✅ Scaled node pool '{pool_name}' to size={size}", fg=typer.colors.GREEN)


cli = NodePools(console)


@node_pools_app.command("list", help="List configured node pools")
def list_pools(
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    cli.list(cluster=cluster)


@node_pools_app.command("show", help="Show node pools config (YAML)")
def show_pools(
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    cli.show(cluster=cluster)


@node_pools_app.command("add", help="Add (or update) a node pool")
def add_pool(
    name: str = typer.Option(..., "--name", help="Node pool name"),
    region: str = typer.Option("global", "--region", help="Node pool region"),
    size: int = typer.Option(0, "--size", help="Number of nodes"),
    provider: str = typer.Option(..., "--provider", help="Provider name"),
    azure_vmss_name: Optional[str] = typer.Option(None, "--azure-vmss-name", help="Azure VMSS name (azure only)"),
    azure_resource_group: Optional[str] = typer.Option(
        None, "--azure-resource-group", help="Azure resource group (azure only)"
    ),
    ssh_username: str = typer.Option("root", "--ssh-username", help="SSH username (default: root)"),
    ssh_password: Optional[str] = typer.Option(None, "--ssh-password", help="SSH password (optional)"),
    ssh_key_path: Optional[str] = typer.Option(None, "--ssh-key-path", help="SSH private key path (optional)"),
    ssh_port: int = typer.Option(22, "--ssh-port", help="SSH port"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
    overwrite: bool = typer.Option(
        False,
        "--overwrite",
        help="Overwrite an existing pool with the same name (otherwise errors)",
    ),
) -> None:
    cli.add(
        name=name,
        region=region,
        size=size,
        provider=provider,
        azure_vmss_name=azure_vmss_name,
        azure_resource_group=azure_resource_group,
        ssh_username=ssh_username,
        ssh_password=ssh_password,
        ssh_key_path=ssh_key_path,
        ssh_port=ssh_port,
        cluster=cluster,
        overwrite=overwrite,
    )


@node_pools_app.command("remove", help="Remove a node pool by name")
def remove_pool(
    pool: Optional[str] = typer.Argument(None, help="Node pool name"),
    name: Optional[str] = typer.Option(None, "--name", help="Node pool name (alternative to positional arg)"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    pool_name = name or pool
    if not pool_name:
        typer.secho("❌ Missing node pool name. Provide it as an argument or via --name.", fg=typer.colors.RED)
        raise typer.Exit(1)

    cli.remove(pool_name=pool_name, cluster=cluster)


@node_pools_app.command("rm", help="Alias for remove")
def rm_pool(
    pool: Optional[str] = typer.Argument(None, help="Node pool name"),
    name: Optional[str] = typer.Option(None, "--name", help="Node pool name (alternative to positional arg)"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    pool_name = name or pool
    if not pool_name:
        typer.secho("❌ Missing node pool name. Provide it as an argument or via --name.", fg=typer.colors.RED)
        raise typer.Exit(1)

    cli.remove(pool_name=pool_name, cluster=cluster)


@node_pools_app.command("scale", help="Scale a node pool to a specific size")
def scale_pool(
    pool: Optional[str] = typer.Argument(None, help="Node pool name"),
    to: Optional[int] = typer.Argument(None, help="New size"),
    name: Optional[str] = typer.Option(None, "--name", help="Node pool name (alternative to positional arg)"),
    size: Optional[int] = typer.Option(None, "--size", help="New size (alternative to positional arg)"),
    cluster: str | None = typer.Option(None, "--cluster", help="Cluster name (uses default if omitted)"),
) -> None:
    pool_name = name or pool
    new_size = size if size is not None else to
    if not pool_name:
        typer.secho("❌ Missing node pool name. Provide it as an argument or via --name.", fg=typer.colors.RED)
        raise typer.Exit(1)
    if new_size is None:
        typer.secho("❌ Missing size. Provide it as an argument or via --size.", fg=typer.colors.RED)
        raise typer.Exit(1)

    cli.scale(pool_name=pool_name, size=new_size, cluster=cluster)
