// Generated by Copilot
// Connectivity Graph visualization component

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Loader, Network, RefreshCw } from 'lucide-react';
import { getConnectivityGraph } from '../api/client';
import type { ConnectivityGraph, GraphNode, GraphEdge } from '../types';
import { formatLatency } from '../types';

interface NodePosition {
  x: number;
  y: number;
  node: GraphNode;
}

interface TooltipState {
  visible: boolean;
  x: number;
  y: number;
  node: GraphNode | null;
  edge: GraphEdge | null;
}

interface ConnectivityGraphViewProps {
  refreshInterval?: number;
}

export const ConnectivityGraphView: React.FC<ConnectivityGraphViewProps> = ({
  refreshInterval = 30000,
}) => {
  const [graphData, setGraphData] = useState<ConnectivityGraph | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [tooltip, setTooltip] = useState<TooltipState>({
    visible: false,
    x: 0,
    y: 0,
    node: null,
    edge: null,
  });

  const fetchGraph = useCallback(async () => {
    try {
      const data = await getConnectivityGraph();
      setGraphData(data);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load graph');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchGraph();
    const interval = setInterval(fetchGraph, refreshInterval);
    return () => clearInterval(interval);
  }, [fetchGraph, refreshInterval]);

  // Calculate node positions in a radial layout
  const nodePositions = useMemo<NodePosition[]>(() => {
    if (!graphData) return [];

    const hubNode = graphData.nodes.find((n) => n.type === 'hub');
    const otherNodes = graphData.nodes.filter((n) => n.type !== 'hub');

    const centerX = 400;
    const centerY = 300;
    const radius = Math.min(250, 80 + otherNodes.length * 20);

    const positions: NodePosition[] = [];

    // Hub in center
    if (hubNode) {
      positions.push({ x: centerX, y: centerY, node: hubNode });
    }

    // Other nodes in a circle
    otherNodes.forEach((node, index) => {
      const angle = (2 * Math.PI * index) / otherNodes.length - Math.PI / 2;
      positions.push({
        x: centerX + radius * Math.cos(angle),
        y: centerY + radius * Math.sin(angle),
        node,
      });
    });

    return positions;
  }, [graphData]);

  // Build edge data with positions
  const edgeData = useMemo(() => {
    if (!graphData || nodePositions.length === 0) return [];

    return graphData.edges.map((edge) => {
      const sourcePos = nodePositions.find((p) => p.node.id === edge.source);
      const targetPos = nodePositions.find((p) => p.node.id === edge.target);
      return { edge, sourcePos, targetPos };
    });
  }, [graphData, nodePositions]);

  // Calculate stats
  const stats = useMemo(() => {
    if (!graphData) return null;

    const successEdges = graphData.edges.filter((e) => e.success);
    const failedEdges = graphData.edges.filter(
      (e) => !e.success && e.measured_at
    );
    const avgLatency =
      successEdges.length > 0
        ? successEdges.reduce((sum, e) => sum + (e.latency_ms || 0), 0) /
          successEdges.length
        : null;

    return {
      totalNodes: graphData.nodes.length,
      totalEdges: graphData.edges.length,
      successCount: successEdges.length,
      failedCount: failedEdges.length,
      avgLatency,
    };
  }, [graphData]);

  const getNodeStatus = (node: GraphNode): string => {
    if (node.type === 'hub') return 'hub';
    if (!node.ready) return 'unreachable';
    if (node.status !== 'Ready') return 'degraded';
    return 'healthy';
  };

  const handleNodeHover = (
    e: React.MouseEvent,
    node: GraphNode,
    entering: boolean
  ) => {
    if (entering) {
      const rect = (e.target as SVGElement)
        .closest('.graph-canvas')
        ?.getBoundingClientRect();
      if (rect) {
        setTooltip({
          visible: true,
          x: e.clientX - rect.left + 10,
          y: e.clientY - rect.top + 10,
          node,
          edge: null,
        });
      }
    } else {
      setTooltip({ visible: false, x: 0, y: 0, node: null, edge: null });
    }
  };

  if (loading && !graphData) {
    return (
      <div className="graph-container">
        <div className="graph-loading">
          <Loader size={48} className="spinning" />
          <p>Loading connectivity graph...</p>
        </div>
      </div>
    );
  }

  if (error && !graphData) {
    return (
      <div className="graph-container">
        <div className="graph-empty">
          <Network size={64} />
          <p>Failed to load graph: {error}</p>
          <button onClick={fetchGraph}>Retry</button>
        </div>
      </div>
    );
  }

  if (!graphData || graphData.nodes.length === 0) {
    return (
      <div className="graph-container">
        <div className="graph-empty">
          <Network size={64} />
          <p>No nodes available</p>
        </div>
      </div>
    );
  }

  return (
    <div className="graph-container">
      <div className="graph-header">
        <h2>Node Connectivity Graph</h2>
        <div className="graph-legend">
          <div className="legend-item">
            <span className="legend-dot hub" />
            <span>Node Manager</span>
          </div>
          <div className="legend-item">
            <span className="legend-dot healthy" />
            <span>Healthy</span>
          </div>
          <div className="legend-item">
            <span className="legend-dot degraded" />
            <span>Degraded</span>
          </div>
          <div className="legend-item">
            <span className="legend-dot unreachable" />
            <span>Unreachable</span>
          </div>
          <button
            onClick={fetchGraph}
            style={{
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              color: 'var(--text-secondary)',
              padding: '4px',
            }}
            title="Refresh"
          >
            <RefreshCw size={16} />
          </button>
        </div>
      </div>

      <div className="graph-canvas">
        <svg className="graph-svg" viewBox="0 0 800 600" preserveAspectRatio="xMidYMid meet">
          {/* Edges */}
          <g className="edges">
            {edgeData.map(({ edge, sourcePos, targetPos }) => {
              if (!sourcePos || !targetPos) return null;

              const midX = (sourcePos.x + targetPos.x) / 2;
              const midY = (sourcePos.y + targetPos.y) / 2;
              const edgeClass = !edge.measured_at
                ? 'no-data'
                : edge.success
                  ? 'success'
                  : 'failure';

              return (
                <g key={`${edge.source}-${edge.target}`}>
                  <line
                    className={`graph-edge ${edgeClass}`}
                    x1={sourcePos.x}
                    y1={sourcePos.y}
                    x2={targetPos.x}
                    y2={targetPos.y}
                  />
                  {edge.measured_at && (
                    <>
                      <rect
                        className="edge-label-bg"
                        x={midX - 22}
                        y={midY - 8}
                        width={44}
                        height={16}
                      />
                      <text className={`edge-label ${edgeClass}`} x={midX} y={midY}>
                        {edge.success
                          ? formatLatency(edge.latency_ms)
                          : 'Failed'}
                      </text>
                    </>
                  )}
                </g>
              );
            })}
          </g>

          {/* Nodes */}
          <g className="nodes">
            {nodePositions.map((pos) => {
              const status = getNodeStatus(pos.node);
              const nodeRadius = pos.node.type === 'hub' ? 40 : 32;

              return (
                <g
                  key={pos.node.id}
                  className="graph-node"
                  transform={`translate(${pos.x}, ${pos.y})`}
                  onMouseEnter={(e) => handleNodeHover(e, pos.node, true)}
                  onMouseLeave={(e) => handleNodeHover(e, pos.node, false)}
                >
                  <circle
                    className={`node-circle ${status}`}
                    r={nodeRadius}
                  />
                  <text className="node-label" y={-4}>
                    {pos.node.label.length > 12
                      ? pos.node.label.slice(0, 10) + '…'
                      : pos.node.label}
                  </text>
                  <text className="node-sublabel" y={10}>
                    {pos.node.type === 'hub'
                      ? 'Hub'
                      : pos.node.ip?.split('.').slice(-2).join('.') || ''}
                  </text>
                </g>
              );
            })}
          </g>
        </svg>

        {/* Tooltip */}
        {tooltip.visible && tooltip.node && (
          <div
            className="node-tooltip"
            style={{ left: tooltip.x, top: tooltip.y }}
          >
            <div className="tooltip-header">
              <span
                className="tooltip-status"
                style={{
                  background:
                    tooltip.node.type === 'hub'
                      ? 'var(--accent)'
                      : tooltip.node.ready
                        ? 'var(--success)'
                        : 'var(--error)',
                }}
              />
              <span className="tooltip-name">{tooltip.node.label}</span>
            </div>
            <div className="tooltip-row">
              <span className="tooltip-label">Type</span>
              <span className="tooltip-value">
                {tooltip.node.type === 'hub' ? 'Node Manager' : 'Cluster Node'}
              </span>
            </div>
            <div className="tooltip-row">
              <span className="tooltip-label">IP</span>
              <span className="tooltip-value">{tooltip.node.ip || 'N/A'}</span>
            </div>
            <div className="tooltip-row">
              <span className="tooltip-label">Status</span>
              <span className="tooltip-value">{tooltip.node.status}</span>
            </div>
            {tooltip.node.type !== 'hub' && (
              <>
                <div className="tooltip-row">
                  <span className="tooltip-label">Kubelet</span>
                  <span className="tooltip-value">
                    {tooltip.node.kubelet_version || 'N/A'}
                  </span>
                </div>
                <div className="tooltip-row">
                  <span className="tooltip-label">CPU</span>
                  <span className="tooltip-value">
                    {tooltip.node.cpu_capacity || 'N/A'}
                  </span>
                </div>
                <div className="tooltip-row">
                  <span className="tooltip-label">Memory</span>
                  <span className="tooltip-value">
                    {tooltip.node.memory_capacity || 'N/A'}
                  </span>
                </div>
              </>
            )}
          </div>
        )}
      </div>

      {stats && (
        <div className="graph-stats">
          <div className="stat-item">
            <span className="stat-label">Nodes:</span>
            <span className="stat-value">{stats.totalNodes}</span>
          </div>
          <div className="stat-item">
            <span className="stat-label">Connections:</span>
            <span className="stat-value">{stats.totalEdges}</span>
          </div>
          <div className="stat-item">
            <span className="stat-label">Successful:</span>
            <span className="stat-value success">{stats.successCount}</span>
          </div>
          {stats.failedCount > 0 && (
            <div className="stat-item">
              <span className="stat-label">Failed:</span>
              <span className="stat-value error">{stats.failedCount}</span>
            </div>
          )}
          {stats.avgLatency !== null && (
            <div className="stat-item">
              <span className="stat-label">Avg Latency:</span>
              <span className="stat-value">{formatLatency(stats.avgLatency)}</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
