// Generated by Copilot
import React from 'react';
import { RefreshCw, Activity, Clock } from 'lucide-react';
import type { HealthStatus } from '../types';

interface HeaderProps {
  health: HealthStatus | null;
  lastUpdated: Date | null;
  onRefresh: () => void;
  loading?: boolean;
}

export const Header: React.FC<HeaderProps> = ({
  health,
  lastUpdated,
  onRefresh,
  loading,
}) => {
  return (
    <header className="app-header">
      <div className="header-left">
        <h1>
          <Activity size={28} />
          Kitchen Node Manager
        </h1>
        {health && (
          <div className={`health-badge ${health.healthy ? 'healthy' : 'error'}`}>
            <span className="health-dot" />
            {health.healthy ? 'System Healthy' : 'Issues Detected'}
          </div>
        )}
      </div>
      <div className="header-right">
        {lastUpdated && (
          <span className="last-update">
            <Clock size={14} />
            Updated {formatTime(lastUpdated)}
          </span>
        )}
        <button
          className="refresh-btn"
          onClick={onRefresh}
          disabled={loading}
          title="Refresh"
        >
          <RefreshCw size={18} className={loading ? 'spinning' : ''} />
        </button>
      </div>
    </header>
  );
};

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}
