// Generated by Copilot
import React from 'react';
import type { NodeWithConnectivity, NodeStatus } from '../types';
import { getNodeStatus, formatLatency, formatTimeAgo } from '../types';
import {
  Server,
  CheckCircle,
  AlertTriangle,
  XCircle,
  Wifi,
  WifiOff,
  Cpu,
  HardDrive,
} from 'lucide-react';

interface NodeCardProps {
  node: NodeWithConnectivity;
  onClick?: (node: NodeWithConnectivity) => void;
  selected?: boolean;
}

const StatusIcon: React.FC<{ status: NodeStatus }> = ({ status }) => {
  switch (status) {
    case 'healthy':
      return <CheckCircle className="status-icon healthy" size={16} />;
    case 'degraded':
      return <AlertTriangle className="status-icon warning" size={16} />;
    case 'unreachable':
      return <XCircle className="status-icon error" size={16} />;
    default:
      return <Server className="status-icon unknown" size={16} />;
  }
};

export const NodeCard: React.FC<NodeCardProps> = ({ node, onClick, selected }) => {
  const status = getNodeStatus(node);
  const latency = node.connectivity?.latency_ms;
  const pingSuccess = node.connectivity?.success ?? null;

  return (
    <div
      className={`node-card ${status} ${selected ? 'selected' : ''}`}
      onClick={() => onClick?.(node)}
    >
      <div className="node-header">
        <div className="node-name">
          <Server size={18} />
          <span>{node.name}</span>
        </div>
        <StatusIcon status={status} />
      </div>

      <div className="node-status-row">
        <span className={`status-badge ${node.ready ? 'ready' : 'not-ready'}`}>
          {node.ready ? 'Ready' : 'Not Ready'}
        </span>
        {!node.schedulable && (
          <span className="status-badge cordoned">Cordoned</span>
        )}
      </div>

      <div className="node-details">
        <div className="detail-row">
          <span className="detail-label">IP</span>
          <span className="detail-value">
            {node.tailscale_ip || node.internal_ip || '—'}
          </span>
        </div>

        <div className="detail-row">
          <span className="detail-label">
            {pingSuccess !== null ? (
              pingSuccess ? (
                <Wifi size={14} className="ping-icon success" />
              ) : (
                <WifiOff size={14} className="ping-icon error" />
              )
            ) : (
              <Wifi size={14} className="ping-icon unknown" />
            )}
            Ping
          </span>
          <span className={`detail-value latency ${getLatencyClass(latency)}`}>
            {formatLatency(latency)}
          </span>
        </div>

        {node.cpu_capacity && (
          <div className="detail-row">
            <span className="detail-label">
              <Cpu size={14} />
              CPU
            </span>
            <span className="detail-value">{node.cpu_capacity}</span>
          </div>
        )}

        {node.memory_capacity && (
          <div className="detail-row">
            <span className="detail-label">
              <HardDrive size={14} />
              RAM
            </span>
            <span className="detail-value">{formatMemory(node.memory_capacity)}</span>
          </div>
        )}
      </div>

      <div className="node-footer">
        <span className="last-seen">
          Updated {formatTimeAgo(node.last_seen_at)}
        </span>
        {node.kubelet_version && (
          <span className="version">{node.kubelet_version}</span>
        )}
      </div>
    </div>
  );
};

function getLatencyClass(ms: number | null | undefined): string {
  if (ms === null || ms === undefined) return '';
  if (ms < 10) return 'excellent';
  if (ms < 50) return 'good';
  if (ms < 100) return 'moderate';
  return 'poor';
}

function formatMemory(mem: string): string {
  // Convert Ki to human readable
  const match = mem.match(/^(\d+)Ki$/);
  if (match) {
    const ki = parseInt(match[1], 10);
    const gi = ki / (1024 * 1024);
    if (gi >= 1) return `${gi.toFixed(1)}Gi`;
    const mi = ki / 1024;
    return `${mi.toFixed(0)}Mi`;
  }
  return mem;
}

interface NodeGridProps {
  nodes: NodeWithConnectivity[];
  selectedNode?: string | null;
  onNodeSelect?: (node: NodeWithConnectivity) => void;
}

export const NodeGrid: React.FC<NodeGridProps> = ({
  nodes,
  selectedNode,
  onNodeSelect,
}) => {
  // Sort nodes: unhealthy first, then by name
  const sortedNodes = [...nodes].sort((a, b) => {
    const statusOrder: Record<NodeStatus, number> = {
      unreachable: 0,
      degraded: 1,
      unknown: 2,
      healthy: 3,
    };
    const aStatus = getNodeStatus(a);
    const bStatus = getNodeStatus(b);
    if (statusOrder[aStatus] !== statusOrder[bStatus]) {
      return statusOrder[aStatus] - statusOrder[bStatus];
    }
    return a.name.localeCompare(b.name);
  });

  return (
    <div className="node-grid">
      {sortedNodes.map((node) => (
        <NodeCard
          key={node.name}
          node={node}
          selected={selectedNode === node.name}
          onClick={onNodeSelect}
        />
      ))}
    </div>
  );
};
