// Generated by Copilot
import React from 'react';
import type { NodeStats, HealthStatus } from '../types';
import {
  Server,
  CheckCircle,
  AlertTriangle,
  XCircle,
  Activity,
  Clock,
} from 'lucide-react';

interface StatsCardsProps {
  stats: NodeStats;
  health: HealthStatus;
}

export const StatsCards: React.FC<StatsCardsProps> = ({ stats, health }) => {
  return (
    <div className="stats-grid">
      <div className="stat-card">
        <div className="stat-icon total">
          <Server size={24} />
        </div>
        <div className="stat-content">
          <div className="stat-value">{stats.total_nodes}</div>
          <div className="stat-label">Total Nodes</div>
        </div>
      </div>

      <div className="stat-card">
        <div className="stat-icon healthy">
          <CheckCircle size={24} />
        </div>
        <div className="stat-content">
          <div className="stat-value">{stats.ready_nodes}</div>
          <div className="stat-label">Ready</div>
        </div>
      </div>

      <div className="stat-card">
        <div className="stat-icon warning">
          <AlertTriangle size={24} />
        </div>
        <div className="stat-content">
          <div className="stat-value">{stats.not_ready_nodes}</div>
          <div className="stat-label">Not Ready</div>
        </div>
      </div>

      <div className="stat-card">
        <div className="stat-icon error">
          <XCircle size={24} />
        </div>
        <div className="stat-content">
          <div className="stat-value">{stats.unavailable_nodes}</div>
          <div className="stat-label">Unavailable</div>
        </div>
      </div>

      <div className="stat-card">
        <div className="stat-icon latency">
          <Activity size={24} />
        </div>
        <div className="stat-content">
          <div className="stat-value">
            {stats.average_latency_ms !== null
              ? `${stats.average_latency_ms.toFixed(1)}ms`
              : '—'}
          </div>
          <div className="stat-label">Avg Latency</div>
        </div>
      </div>

      <div className="stat-card">
        <div className={`stat-icon ${health.healthy ? 'healthy' : 'error'}`}>
          <Clock size={24} />
        </div>
        <div className="stat-content">
          <div className="stat-value">
            {health.worker_running ? 'Active' : 'Stopped'}
          </div>
          <div className="stat-label">Monitor</div>
        </div>
      </div>
    </div>
  );
};
