// API client for Kitchen Node Manager

import type {
  HealthStatus,
  NodeStats,
  NodeWithConnectivity,
  NodeDetail,
  ConnectivityRecord,
  ConnectivitySummary,
  ConnectivityGraph,
} from '../types';

const API_BASE = '';

async function fetchJson<T>(url: string): Promise<T> {
  const response = await fetch(`${API_BASE}${url}`);
  if (!response.ok) {
    throw new Error(`API error: ${response.status} ${response.statusText}`);
  }
  return response.json();
}

export async function getHealth(): Promise<HealthStatus> {
  return fetchJson<HealthStatus>('/health');
}

export async function getStats(): Promise<NodeStats> {
  return fetchJson<NodeStats>('/stats');
}

export async function getNodesDashboard(): Promise<NodeWithConnectivity[]> {
  return fetchJson<NodeWithConnectivity[]>('/nodes/dashboard');
}

export async function getNodeDetail(name: string): Promise<NodeDetail> {
  return fetchJson<NodeDetail>(`/nodes/${encodeURIComponent(name)}`);
}

export async function getNodeConnectivity(
  name: string,
  hours: number = 24
): Promise<ConnectivityRecord[]> {
  return fetchJson<ConnectivityRecord[]>(
    `/nodes/${encodeURIComponent(name)}/connectivity?hours=${hours}`
  );
}

// Generated by Copilot
export interface ConnectivityHistoryOptions {
  limit?: number;
  sourceNode?: string;
  success?: boolean;
}

export async function getNodeConnectivityHistory(
  name: string,
  options: ConnectivityHistoryOptions = {}
): Promise<ConnectivityRecord[]> {
  const params = new URLSearchParams();
  if (options.limit !== undefined) params.append('limit', options.limit.toString());
  if (options.sourceNode !== undefined) params.append('source_node', options.sourceNode);
  if (options.success !== undefined) params.append('success', options.success.toString());
  
  const query = params.toString();
  return fetchJson<ConnectivityRecord[]>(
    `/nodes/${encodeURIComponent(name)}/connectivity/history${query ? `?${query}` : ''}`
  );
}

export async function getLatestConnectivity(): Promise<ConnectivitySummary[]> {
  return fetchJson<ConnectivitySummary[]>('/connectivity/latest');
}

export async function getConnectivityGraph(): Promise<ConnectivityGraph> {
  return fetchJson<ConnectivityGraph>('/connectivity/graph');
}

// Polling hook data types
export interface DashboardData {
  health: HealthStatus;
  stats: NodeStats;
  nodes: NodeWithConnectivity[];
}

export async function getDashboardData(): Promise<DashboardData> {
  const [health, stats, nodes] = await Promise.all([
    getHealth(),
    getStats(),
    getNodesDashboard(),
  ]);
  return { health, stats, nodes };
}
