"""Node provider abstractions.

This package contains provider-specific implementations for managing node pools.
"""
# Generated by Copilot

from .base import NodeProvider
from .azure import AzureNodeProvider

__all__ = ["NodeProvider", "AzureNodeProvider"]
