"""Azure node provider implementation."""
# Generated by Copilot

from __future__ import annotations

import logging
import shutil
import subprocess

from .base import NodeProvider


logger = logging.getLogger(__name__)


class AzureNodeProvider(NodeProvider):
    """Azure implementation of the NodeProvider interface.

    Uses Azure CLI (az) under the hood.
    """

    def __init__(self, *, vmss_name: str, resource_group: str) -> None:
        az_path = shutil.which("az")
        if not az_path:
            raise RuntimeError(
                "Azure CLI ('az') not found in PATH. Install it to use the Azure node provider."
            )

        self._az_path = az_path
        self._vmss_name = (vmss_name or "").strip()
        self._resource_group = (resource_group or "").strip()

        if not self._vmss_name or not self._resource_group:
            raise ValueError("vmss_name and resource_group are required")

        logger.info(
            "Using Azure CLI at: %s (vmss=%s rg=%s)",
            self._az_path,
            self._vmss_name,
            self._resource_group,
        )

    def scale_pool(self, name: str, size: int) -> str | None:
        if size < 0:
            raise ValueError("size must be >= 0")

        cmd = [
            self._az_path,
            "vmss",
            "scale",
            "--name",
            self._vmss_name,
            "--resource-group",
            self._resource_group,
            "--new-capacity",
            str(size),
        ]

        logger.info(
            "Azure scale_pool pool=%s vmss=%s rg=%s size=%s",
            name,
            self._vmss_name,
            self._resource_group,
            size,
        )

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            details = (result.stderr or result.stdout or "").strip()
            raise RuntimeError(f"az vmss scale failed (exit {result.returncode}): {details}")

        stdout = (result.stdout or "").strip()
        stderr = (result.stderr or "").strip()
        if stdout and stderr:
            return stdout + "\n" + stderr
        return stdout or stderr or None
