"""Provider interface for managing node pools.

A node provider is responsible for performing provider-specific operations such as
scaling node pools.
"""
# Generated by Copilot

from __future__ import annotations

from abc import ABC, abstractmethod


class NodeProvider(ABC):
    """Abstract base class for node providers."""

    @abstractmethod
    def scale_pool(self, name: str, size: int) -> str | None:
        """Scale the node pool to the desired size.

        Args:
            name: Node pool name.
            size: Target size (must be >= 0).
        """

        raise NotImplementedError
