// Generated by Copilot
import { useState, useEffect, useCallback } from 'react';
import { getDashboardData, type DashboardData } from '../api/client';
import { useWebSocket, type WebSocketMessage } from './useWebSocket';

export function useDashboard(refreshInterval: number = 30000) {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);

  const refresh = useCallback(async () => {
    try {
      const result = await getDashboardData();
      setData(result);
      setError(null);
      setLastUpdated(new Date());
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to fetch data');
    } finally {
      setLoading(false);
    }
  }, []);

  // Handle WebSocket messages for live updates
  const handleWebSocketMessage = useCallback((message: WebSocketMessage) => {
    if (message.type === 'dashboard' && message.data) {
      setData((prev) => {
        if (!prev) return prev;
        
        return {
          ...prev,
          stats: message.data.stats
            ? { ...prev.stats, ...message.data.stats }
            : prev.stats,
          nodes: message.data.nodes ?? prev.nodes,
        };
      });
      setLastUpdated(new Date());
    }
  }, []);

  const { isConnected } = useWebSocket({
    onMessage: handleWebSocketMessage,
  });

  // Initial load
  useEffect(() => {
    refresh();
  }, [refresh]);

  // Fallback polling when WebSocket is disconnected
  useEffect(() => {
    if (isConnected) return; // WebSocket handles updates
    
    const interval = setInterval(refresh, refreshInterval);
    return () => clearInterval(interval);
  }, [refresh, refreshInterval, isConnected]);

  return { data, loading, error, lastUpdated, refresh, isConnected };
}
