"""
Configuration models for Kitchen.
"""
# Generated by Copilot
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass(slots=True)
class NodePoolSSH:
    """SSH configuration for a node pool.

    Attributes:
        username: SSH username for connecting to nodes in this pool (default: root).
        password: Optional SSH password (if not using keys).
        key_path: Optional path to SSH private key.
        port: SSH port (default 22).
    """

    username: str = "root"
    password: Optional[str] = None
    key_path: Optional[str] = None
    port: int = 22


@dataclass(slots=True)
class NodePoolAzureConfig:
    """Azure-specific configuration for a node pool.

    Attributes:
        vmss_name: Azure VM Scale Set name.
        resource_group: Azure Resource Group containing the VMSS.
    """

    vmss_name: str
    resource_group: str


@dataclass(slots=True)
class NodePoolAwsConfig:
    """AWS-specific configuration for a node pool.

    Attributes:
        asg_name: AWS Auto Scaling Group name.
        region: AWS region.
    """

    asg_name: str
    region: str = "us-east-1"


@dataclass(slots=True)
class NodePool:
    """Configuration for a node pool.

    Attributes:
        name: Unique name for the node pool.
        region: Region for the node pool (default: global).
        size: Number of nodes in this pool.
        provider: Infrastructure provider (e.g., 'hetzner', 'aws', 'bare-metal').
        ssh: SSH configuration for accessing nodes in this pool.
    """

    name: str
    size: int
    provider: str
    ssh: NodePoolSSH
    region: str = "global"
    azure: Optional[NodePoolAzureConfig] = None
    aws: Optional[NodePoolAwsConfig] = None


@dataclass(slots=True)
class NodePoolsConfig:
    """Node pools configuration container.

    Attributes:
        node_pools: List of node pool configurations.
    """

    node_pools: List[NodePool] = field(default_factory=list)


@dataclass(slots=True)
class MasterNodeConfig:
    """Configuration for the master node.

    Attributes:
        hostname: The hostname of the master node.
        ips: A list of IP addresses for the master node (e.g., Tailscale, LAN).
        kubernetes_version: Desired Kubernetes version (e.g., "1.29"). Optional; latest stable if None.
    """

    hostname: str
    ips: List[str] = field(default_factory=list)
    kubernetes_version: Optional[str] = None


@dataclass(slots=True)
class ClusterSecrets:
    """Secrets associated with a cluster; stored locally per cluster in a separate file.

    Attributes:
        tailscale_auth_key: Auth key used for `tailscale up` on nodes.
        discovery_token_ca_cert_hash: kubeadm discovery token CA cert hash (sha256:...).
        kubeadm_token: Optional kubeadm bootstrap token (token[:].tokenid). Not required for all flows.
    """

    tailscale_auth_key: Optional[str] = None
    discovery_token_ca_cert_hash: Optional[str] = None
    kubeadm_token: Optional[str] = None


@dataclass(slots=True)
class ClusterConfig:
    """Complete cluster configuration combining master, secrets, and node pools.

    Attributes:
        name: Cluster name.
        master: Master node configuration.
        secrets: Cluster secrets (may be empty).
        node_pools: Node pools configuration (may be empty).
    """

    name: str
    master: Optional[MasterNodeConfig] = None
    secrets: Optional[ClusterSecrets] = None
    node_pools: Optional[NodePoolsConfig] = None
