// Generated by Copilot
import React, { useState } from 'react';
import { useDashboard } from './hooks/useDashboard';
import { Header } from './components/Header';
import { StatsCards } from './components/StatsCards';
import { NodeGrid } from './components/NodeCard';
import { NodeDetailPanel } from './components/NodeDetailPanel';
import type { NodeWithConnectivity } from './types';
import { AlertTriangle, Loader } from 'lucide-react';
import './styles.css';

const App: React.FC = () => {
  const { data, loading, error, lastUpdated, refresh } = useDashboard(30000);
  const [selectedNode, setSelectedNode] = useState<NodeWithConnectivity | null>(
    null
  );

  if (loading && !data) {
    return (
      <div className="app-root">
        <div className="loading-screen">
          <Loader size={48} className="spinning" />
          <p>Loading dashboard...</p>
        </div>
      </div>
    );
  }

  if (error && !data) {
    return (
      <div className="app-root">
        <div className="error-screen">
          <AlertTriangle size={48} />
          <h2>Failed to load dashboard</h2>
          <p>{error}</p>
          <button onClick={refresh}>Retry</button>
        </div>
      </div>
    );
  }

  if (!data) return null;

  return (
    <div className="app-root">
      <Header
        health={data.health}
        lastUpdated={lastUpdated}
        onRefresh={refresh}
        loading={loading}
      />

      <main className="app-main">
        <div className="dashboard-content">
          <section className="stats-section">
            <StatsCards stats={data.stats} health={data.health} />
          </section>

          <section className="nodes-section">
            <div className="section-header">
              <h2>Nodes ({data.nodes.length})</h2>
            </div>
            <NodeGrid
              nodes={data.nodes}
              selectedNode={selectedNode?.name}
              onNodeSelect={setSelectedNode}
            />
          </section>
        </div>

        {selectedNode && (
          <aside className="detail-sidebar">
            <NodeDetailPanel
              node={selectedNode}
              onClose={() => setSelectedNode(null)}
            />
          </aside>
        )}
      </main>

      <footer className="app-footer">
        <span>Kitchen Node Manager</span>
        <span className="footer-sep">•</span>
        <span>
          {data.health.kubernetes_healthy
            ? 'Kubernetes Connected'
            : 'Kubernetes Disconnected'}
        </span>
        <span className="footer-sep">•</span>
        <span>Auto-refresh: 30s</span>
      </footer>
    </div>
  );
};

export default App;
