// Generated by Copilot
// Type definitions for Kitchen Node Manager API

export interface HealthStatus {
  healthy: boolean;
  kubernetes_healthy: boolean;
  ping_available: boolean;
  worker_running: boolean;
  monitoring_task_running: boolean;
  connectivity_task_running: boolean;
  database_healthy: boolean;
  node_count: number;
  last_monitoring_cycle: string | null;
}

export interface NodeStats {
  total_nodes: number;
  ready_nodes: number;
  not_ready_nodes: number;
  unavailable_nodes: number;
  nodes_with_tailscale: number;
  average_latency_ms: number | null;
}

export interface ConnectivitySummary {
  node_name: string;
  target_ip: string;
  success: boolean;
  latency_ms: number | null;
  packet_loss: number | null;
  measured_at: string;
}

export interface NodeSummary {
  name: string;
  status: string;
  ready: boolean;
  schedulable: boolean;
  internal_ip: string | null;
  tailscale_ip: string | null;
  kubelet_version: string | null;
  first_seen_at: string;
  last_seen_at: string;
  unavailable_since: string | null;
}

export interface NodeWithConnectivity extends NodeSummary {
  os_image: string | null;
  cpu_capacity: string | null;
  memory_capacity: string | null;
  connectivity: ConnectivitySummary | null;
}

export interface NodeDetail extends NodeSummary {
  external_ip: string | null;
  hostname: string | null;
  container_runtime: string | null;
  os_image: string | null;
  kernel_version: string | null;
  cpu_capacity: string | null;
  memory_capacity: string | null;
  pods_capacity: number | null;
  node_created_at: string | null;
}

export interface ConnectivityRecord {
  node_name: string;
  target_ip: string;
  success: boolean;
  latency_ms: number | null;
  packet_loss: number | null;
  error_message: string | null;
  ping_count: number;
  measured_at: string;
}

export type NodeStatus = 'healthy' | 'degraded' | 'unreachable' | 'unknown';

export function getNodeStatus(node: NodeWithConnectivity): NodeStatus {
  if (node.unavailable_since) return 'unreachable';
  if (!node.ready) return 'degraded';
  if (node.connectivity && !node.connectivity.success) return 'degraded';
  if (node.ready && (!node.connectivity || node.connectivity.success)) return 'healthy';
  return 'unknown';
}

export function formatLatency(ms: number | null | undefined): string {
  if (ms === null || ms === undefined) return '—';
  if (ms < 1) return '<1ms';
  return `${ms.toFixed(1)}ms`;
}

export function formatTimeAgo(dateStr: string | null): string {
  if (!dateStr) return 'Never';
  const date = new Date(dateStr);
  const now = new Date();
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}
